export const organizationData = {
  director: {
    id: 1,
    name: 'Allo Hui',
    position: 'IT & Operations Director',
    company: 'FunctionEight',
    image: '/avatars/HK - Allo Hui.png',
  },
  managers: [
    {
      id: 2,
      name: 'Kay Yeung',
      position: 'IT Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Kay Yeung.png',
      employees: [
        { id: 4, name: 'Derek Lai', position: 'System Engineer', image: '/avatars/HK - Derek Lai.png'},
        { id: 5, name: 'Harold Sit', position: 'System Engineer', image: '/avatars/HK - Harold Sit.png'},
        { id: 6, name: 'Alvin Luk', position: 'System Engineer', image: '/avatars/HK - Alvin Luk.png'},
        { id: 7, name: 'Justin Chung', position: 'System Engineer', image: '/avatars/HK - Justin Chung.png'},
        { id: 8, name: 'Victor Cheng', position: 'System Engineer', image: '/avatars/HK - Victor Cheng.png'},
      ],
      clients: [
        {
          id: 101,
          name: 'Oval',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Derek Lai'],
          tier: 'tier-b',
        },
        {
          id: 102,
          name: 'H Properties',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 103,
          name: 'Triide',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 104,
          name: 'Limetree',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 105,
          name: 'EAL',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 106,
          name: 'EIP',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-b',
        },
        {
          id: 107,
          name: 'Perfectos',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-b',
        },
        {
          id: 108,
          name: 'Rockpool',
          fullCompanyName: 'Rockpool Capital Limited',
          type: 'Recurring',
          hoursPurchased: '10 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Kay Yeung'],
          tier: '',
        },
        {
          id: 109,
          name: 'NPL',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: '',
        },
        {
          id: 111,
          name: 'Apeiron (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-b',
        },
        {
          id: 112,
          name: 'Funville',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-b',
        },
        {
          id: 113,
          name: 'Hauck',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-c',
        },
        {
          id: 114,
          name: 'EGIS',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Victor Cheng'],
          tier: 'tier-a',
        },
        {
          id: 115,
          name: 'APLMA',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-c',
        },
        {
          id: 116,
          name: 'KYO Capital',
          fullCompanyName: 'KYO Capital Limited',
          type: 'Recurring',
          hoursPurchased: 'Mixture of onsite and remote support - Up to 2 hours onsite per month - No carry-forward (accumulation) of monthly hours are allowed',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 117,
          name: 'Connect',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 118,
          name: 'TTA',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 119,
          name: 'CCCL',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-b',
        },
        {
          id: 120,
          name: 'Fidinam',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-c',
        },
        {
          id: 121,
          name: 'Letters & Thoo',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 122,
          name: 'R. Lewis Sanders',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 124,
          name: 'Signal 8',
          fullCompanyName: 'Signal 8 Security',
          type: 'Recurring',
          hoursPurchased: '20 hours ONSITE Support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 126,
          name: 'Zaaba',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-c',
        },
        {
          id: 127,
          name: 'Zaha',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Derek Lai'],
          tier: 'tier-c',
        },
        {
          id: 128,
          name: 'Naga',
          fullCompanyName: 'Naga Brands Limited',
          type: 'Prepaid',
          hoursPurchased: '10 Hours support & Cybersecurity',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 129,
          name: 'Austcham',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-d',
        },
        {
          id: 130,
          name: 'Grace',
          fullCompanyName: 'NG Wing Chee Grace',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 131,
          name: 'Cotton on',
          fullCompanyName: 'Cotton On Hong Kong Limited',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 132,
          name: 'Zhao Da',
          fullCompanyName: 'Zhao Da Global Ltd',
          type: 'Prepaid',
          hoursPurchased: '10 Hours - Mixture of Onsite & Remote Support - Min Onsite 1 Hour - Min Remote Support 15 Mins',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 133,
          name: 'CAIA',
          fullCompanyName: 'CAIA Association Hong Kong Ltd',
          type: 'Prepaid',
          hoursPurchased: '20 Hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 134,
          name: 'Pathos',
          fullCompanyName: 'Pathos Consultancy Limited',
          type: 'Prepaid',
          hoursPurchased: '10 hours - Mixture of onsite and remote support - Hours cover work in Hong Kong & Singapore',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 135,
          name: 'Destination China',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 136,
          name: 'Sedona',
          fullCompanyName: 'Sedona Hong Kong Limited',
          type: 'Prepaid',
          hoursPurchased: '15 hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 137,
          name: 'Weichert',
          fullCompanyName: 'Weichert Companies',
          type: 'Prepaid',
          hoursPurchased: '50 hours - Onsite support, Procurement, Laptop setups, IT related Customer projects',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 139,
          name: 'UIB (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Victor Cheng'],
          tier: 'tier-b',
        },
        {
          id: 140,
          name: 'Chin Teik (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: '',
        },
        {
          id: 141,
          name: 'Sphere (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-b',
        },
        {
          id: 142,
          name: 'Albarine',
          fullCompanyName: 'Albarine Limited',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 143,
          name: 'Broadsword',
          fullCompanyName: 'Broadsword Event House Asia Pacific Limited',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 144,
          name: 'Exellar',
          fullCompanyName: 'Exellar Consulting Pte Ltd',
          type: 'Prepaid',
          hoursPurchased: '6 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Options',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 146,
          name: 'Red Bull',
          fullCompanyName: 'Red Bull Hong Kong Limited',
          type: 'Prepaid',
          hoursPurchased: '5 + 1 (c/f) hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 3,
      name: 'Kenneth Ip',
      position: 'Assistant IT Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Kenneth Ip.png',
      employees: [
        { id: 7, name: 'Russell Wan', position: 'System Engineer', image: '/avatars/HK - Russell.png'},
      ],
      clients: [
        {
          id: 140,
          name: 'Ninemasts (BCT)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-a',
        },
        {
          id: 141,
          name: 'BCT Others',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-a',
        },
        {
          id: 143,
          name: 'TTB (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Russell Wan'],
          tier: 'tier-c',
        },
        {
          id: 144,
          name: 'Buddy Finance',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-c',
        },
        {
          id: 145,
          name: 'Kavod',
          fullCompanyName: 'Bondfull Inc Ltd',
          type: 'Prepaid',
          hoursPurchased: '10 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Aletheia',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-c',
        },
        {
          id: 145,
          name: 'Obsidian',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Lion Rock',
          fullCompanyName: 'Lion Rock Construction Limited',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Long Corridor',
          type: 'Prepaid',
          hoursPurchased: '3 hours support - Coordination of issues or troubleshooting connected to IT and your services',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 4,
      name: 'Samuel Wong',
      position: 'Project Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Samuel Wong.png',
      employees: [
        { id: 10, name: 'Tony Li', position: 'System Engineer', image: '/avatars/HK - Tony Li.png'},
        { id: 11, name: 'Kin Leung', position: 'System Engineer', image: '/avatars/HK - Kin Leung.png'},
        { id: 12, name: 'Steve Wong', position: 'System Engineer', image: '/avatars/HK - Steve Wong.png'},
      ],
      clients: [
        {
          id: 146,
          name: 'Rugby',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Tony Li'],
          tier: 'tier-a',
        },
        {
          id: 147,
          name: 'SPCA',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Kin Leung', 'Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 148,
          name: "Mother's Choice",
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Steve Wong'],
          tier: 'tier-a',
        },
        {
          id: 150,
          name: 'Nexus Point',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 151,
          name: 'Apeiron',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-b',
        },
        {
          id: 151,
          name: 'Ceratec',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Charlton',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Endava (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 151,
          name: 'Jinshi',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'OVC',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Tony Li', 'Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'True Fame (LPM)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 151,
          name: 'Zuma',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'Cathay Vest',
          fullCompanyName: 'CathyVest Capital Management Limited',
          type: 'Prepaid',
          hoursPurchased: '30 hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Horace W',
          fullCompanyName: 'Horace Wong',
          type: 'Prepaid',
          hoursPurchased: '50 hours',
          coreServices: ['Service Desk', 'IT support and Management'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Skyway Pacific',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Arts of Asia',
          fullCompanyName: 'Arts of Asia Publications Ltd',
          type: 'Prepaid',
          hoursPurchased: '10 hours - Remote support primarily, onsite only if needed',
          coreServices: ['Service Desk', 'IT Support for Office 365 License'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Barker',
          fullCompanyName: 'Barker Partner',
          type: 'Prepaid',
          hoursPurchased: '15 hours - Mixture of oniste & remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'CCW',
          fullCompanyName: 'CCW Global Limited',
          type: 'Prepaid',
          hoursPurchased: '50 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Jellycat',
          fullCompanyName: 'JellyCat Ltd.',
          type: 'Prepaid',
          hoursPurchased: '50 hours support 1. Procurement support - Minimum deduction of 1.5 hours per user/issue raised. 2. Remote support - Minimum deduction of 1 hour(s) per issue raised 3. Consultation support - Minimum deduction of 1 hour(s) per issue raised 4. Digital support - Minimum deduction of 1 hour(s) per issue raised',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Langtech',
          fullCompanyName: 'Langtech Limited',
          type: 'Prepaid',
          hoursPurchased: '10 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'P2 Wireless',
          fullCompanyName: 'P2 Wireless Technologies',
          type: 'Prepaid',
          hoursPurchased: '5 Hours support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Stoneview (SG)',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 14,
      name: 'Teflon Siu',
      position: 'Senior System Engineer',
      company: 'FunctionEight',
      image: '/avatars/HK - Teflon Siu.png',
      employees: [
        { id: 11, name: '', position: '', image: ''},
      ],
      clients: [
        {
          id: 151,
          name: 'Pharo',
          fullCompanyName: 'Pharo Management (HK) Limited',
          type: 'Recurring',
          hoursPurchased: '50 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-a',
        },
        {
          id: 152,
          name: 'China Silver',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 153,
          name: 'Profile (Wilson Grp)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-c',
        },
        {
          id: 154,
          name: 'Native Union',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 155,
          name: 'Tradition Capital',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 156,
          name: 'Resolution Chambers',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-c',
        },
        {
          id: 157,
          name: 'White Cube',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Conran',
          fullCompanyName: 'Conran & Partners (HK) Ltd',
          type: 'Recurring',
          hoursPurchased: '10 hours - ONSITE Support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Made Partners',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Audacy',
          fullCompanyName: 'Audacy Ventures',
          type: 'Prepaid',
          hoursPurchased: '15 hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Augventive',
          fullCompanyName: 'Augventive Limited',
          type: 'Prepaid',
          hoursPurchased: '15 Hours',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Design Pool',
          fullCompanyName: 'Design Pool Limited',
          type: 'Prepaid',
          hoursPurchased: '30 Hours - Mixture of onsite and remote support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Glenor Cask',
          fullCompanyName: 'Glenor Cask Company Limited',
          type: 'Prepaid',
          hoursPurchased: '15 Hours - Mixture of Onsite & Remote Support',
          coreServices: ['Standard IT Support'],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 18,
      name: 'Alvin Wong',
      position: 'Enterprise Architect',
    company: 'FunctionEight',
      image: '/avatars/HK - Alvin Wong.png',
      employees: [
        { id: 19, name: 'Kelvin Hui', position: 'System Engineer', image: '/avatars/HK - Kelvin Hui.png' },
      ],
      clients: [
      ],
    },
    {
      id: 22,
      name: 'Harris Leong',
      position: 'Lead, Service Desk',
    company: 'FunctionEight',
      image: '/avatars/HK - Harris Leong.png',
      employees: [
        { id: 23, name: 'Jacky Wong', position: 'System Engineer', image: '/avatars/HK - Jacky Wong.png' },
        { id: 24, name: 'John Wong', position: 'System Engineer', image: '/avatars/HK - John Wong.png' },
      ],
      clients: [
        {
          id: 159,
          name: 'CCCL',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Jacky Wong'],
          tier: '',
        },
        {
          id: 160,
          name: 'Connect',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'John Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Letters & Thoo',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung',],
          tier: '',
        },
        {
          id: 161,
          name: 'R. Lewis Sanders',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung',],
          tier: '',
        },
        {
          id: 161,
          name: 'Austcham',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Harris Leong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Destination China',
          fullCompanyName: 'Destination China Company Limited',
          type: 'Prepaid',
          hoursPurchased: '10 hours - Mixture of onsite and remote support (20% Discounted)',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Exellar',
          fullCompanyName: 'Exellar Consulting Pte Ltd',
          type: 'Prepaid',
          hoursPurchased: '6 hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Kay Yeung', 'Alvin Luk'],
          tier: '',
        },
        {
          id: 161,
          name: 'Naga',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Sedona',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Obsidian',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'TTB (SG)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Ceratec',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Charlton',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Mother\'s Choice',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong', 'Steve Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Nexus Point',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'SPCA',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'True Fame (LPM)',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Zuma',
          type: 'Recurring',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Cathay Vest',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Horace W',
          type: 'Prepaid',
          hoursPurchased: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Skyway Pacific',
          type: 'Prepaid',
          hoursPurchased: '20 hours - Mixture of onsite and remote support',
          coreServices: ['Service Desk', 'Standard IT Support'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
      ],
    },
    {
      id: 26,
      name: 'Casey Tang',
      position: 'Sales Admin',
    company: 'FunctionEight',
      image: '/avatars/HK - Casey Tang.png',
      employees: [
      ],
      clients: [
      ],
    },
  ],
};