export const organizationData = {
  director: {
    id: 1,
    name: 'Allo Hui',
    position: 'IT & Operations Director',
    company: 'FunctionEight',
    image: '/avatars/HK - Allo Hui.png',
  },
  managers: [
    {
      id: 2,
      name: 'Kay Yeung',
      position: 'IT Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Kay Yeung.png',
      employees: [
        { id: 4, name: 'Derek Lai', position: 'System Engineer', image: '/avatars/HK - Derek Lai.png'},
        { id: 5, name: 'Harold Sit', position: 'System Engineer', image: '/avatars/HK - Harold Sit.png'},
        { id: 6, name: 'Alvin Luk', position: 'System Engineer', image: '/avatars/HK - Alvin Luk.png'},
        { id: 7, name: 'Justin Chung', position: 'System Engineer', image: '/avatars/HK - Justin Chung.png'},
        { id: 8, name: 'Victor Cheng', position: 'System Engineer', image: '/avatars/HK - Victor Cheng.png'},
      ],
      clients: [
        {
          id: 101,
          name: 'Oval',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Derek Lai'],
          tier: 'tier-b',
        },
        {
          id: 102,
          name: 'H Properties',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 103,
          name: 'Triide',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 104,
          name: 'Limetree',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 105,
          name: 'EAL',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-a',
        },
        {
          id: 106,
          name: 'EIP',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-b',
        },
        {
          id: 107,
          name: 'Perfectos',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-b',
        },
        {
          id: 108,
          name: 'Rockpool',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: '',
        },
        {
          id: 109,
          name: 'NPL',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: '',
        },
        {
          id: 111,
          name: 'Apeiron (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-b',
        },
        {
          id: 112,
          name: 'Funville',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-b',
        },
        {
          id: 113,
          name: 'Hauck',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-c',
        },
        {
          id: 114,
          name: 'EGIS',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Victor Cheng'],
          tier: 'tier-a',
        },
        {
          id: 115,
          name: 'APLMA',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-c',
        },
        {
          id: 116,
          name: 'KYO Capital',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 117,
          name: 'Connect',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 118,
          name: 'TTA',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 119,
          name: 'CCCL',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-b',
        },
        {
          id: 120,
          name: 'Fidinam',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-c',
        },
        {
          id: 121,
          name: 'Letters & Thoo',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-c',
        },
        {
          id: 122,
          name: 'R. Lewis Sanders',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 124,
          name: 'Signal 8',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 126,
          name: 'Zaaba',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-c',
        },
        {
          id: 127,
          name: 'Zaha',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Derek Lai'],
          tier: 'tier-c',
        },
        {
          id: 128,
          name: 'Naga',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 129,
          name: 'Austcham',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Harold Sit'],
          tier: 'tier-d',
        },
        {
          id: 130,
          name: 'Grace',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 131,
          name: 'Cotton on',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 132,
          name: 'Zhao Da',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 133,
          name: 'CAIA',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 134,
          name: 'Pathos',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 135,
          name: 'Destination China',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 136,
          name: 'Sedona',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 137,
          name: 'Weichert',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 139,
          name: 'UIB (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Victor Cheng'],
          tier: 'tier-b',
        },
        {
          id: 140,
          name: 'Chin Teik (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung'],
          tier: '',
        },
        {
          id: 141,
          name: 'Sphere (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-b',
        },
        {
          id: 142,
          name: 'Albarine',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kay Yeung'],
          tier: 'tier-d',
        },
        {
          id: 143,
          name: 'Broadsword',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 144,
          name: 'Exellar',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Options',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
        {
          id: 146,
          name: 'Red Bull',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Alvin Luk'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 3,
      name: 'Kenneth Ip',
      position: 'Assistant IT Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Kenneth Ip.png',
      employees: [
        { id: 7, name: 'Russell Wan', position: 'System Engineer', image: '/avatars/HK - Russell.png'},
      ],
      clients: [
        {
          id: 140,
          name: 'Ninemasts (BCT)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-a',
        },
        {
          id: 141,
          name: 'BCT Others',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-a',
        },
        {
          id: 143,
          name: 'TTB (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Russell Wan'],
          tier: 'tier-c',
        },
        {
          id: 144,
          name: 'Buddy Finance',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-c',
        },
        {
          id: 145,
          name: 'Kavod',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Aletheia',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-c',
        },
        {
          id: 145,
          name: 'Obsidian',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Lion Rock',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kenneth Ip'],
          tier: 'tier-d',
        },
        {
          id: 145,
          name: 'Long Corridor',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Justin Chung'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 4,
      name: 'Samuel Wong',
      position: 'Project Manager',
      company: 'FunctionEight',
      image: '/avatars/HK - Samuel Wong.png',
      employees: [
        { id: 10, name: 'Tony Li', position: 'System Engineer', image: '/avatars/HK - Tony Li.png'},
        { id: 11, name: 'Kin Leung', position: 'System Engineer', image: '/avatars/HK - Kin Leung.png'},
        { id: 12, name: 'Steve Wong', position: 'System Engineer', image: '/avatars/HK - Steve Wong.png'},
      ],
      clients: [
        {
          id: 146,
          name: 'Rugby',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Tony Li'],
          tier: 'tier-a',
        },
        {
          id: 147,
          name: 'SPCA',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Kin Leung', 'Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 148,
          name: "Mother's Choice",
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Steve Wong'],
          tier: 'tier-a',
        },
        {
          id: 150,
          name: 'Nexus Point',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 151,
          name: 'Apeiron',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-b',
        },
        {
          id: 151,
          name: 'Ceratec',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Charlton',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Endava (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 151,
          name: 'Jinshi',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'OVC',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Tony Li', 'Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'True Fame (LPM)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-a',
        },
        {
          id: 151,
          name: 'Zuma',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-c',
        },
        {
          id: 151,
          name: 'Cathay Vest',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Horace W',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Skyway Pacific',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Arts of Asia',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Barker',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'CCW',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Jellycat',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Langtech',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'P2 Wireless',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
        {
          id: 151,
          name: 'Stoneview (SG)',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Samuel Wong'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 14,
      name: 'Teflon Siu',
      position: 'Senior System Engineer',
    company: 'FunctionEight',
      image: '/avatars/HK - Teflon Siu.png',
      employees: [
      ],
      clients: [
        {
          id: 151,
          name: 'Pharo',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-a',
        },
        {
          id: 152,
          name: 'China Silver',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 153,
          name: 'Profile (Wilson Grp)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-c',
        },
        {
          id: 154,
          name: 'Native Union',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 155,
          name: 'Tradition Capital',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 156,
          name: 'Resolution Chambers',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-c',
        },
        {
          id: 157,
          name: 'White Cube',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Conran',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Made Partners',
          type: 'Recurring',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Audacy',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Augventive',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Design Pool',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
        {
          id: 158,
          name: 'Glenor Cask',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: [''],
          engineeringTeam: ['Teflon Siu'],
          tier: 'tier-d',
        },
      ],
    },
    {
      id: 18,
      name: 'Alvin Wong',
      position: 'Enterprise Architect',
    company: 'FunctionEight',
      image: '/avatars/HK - Alvin Wong.png',
      employees: [
        { id: 19, name: 'Kelvin Hui', position: 'System Engineer', image: '/avatars/HK - Kelvin Hui.png' },
      ],
      clients: [
      ],
    },
    {
      id: 22,
      name: 'Harris Leong',
      position: 'Lead, Service Desk',
    company: 'FunctionEight',
      image: '/avatars/HK - Harris Leong.png',
      employees: [
        { id: 23, name: 'Jacky Wong', position: 'System Engineer', image: '/avatars/HK - Jacky Wong.png' },
        { id: 24, name: 'John Wong', position: 'System Engineer', image: '/avatars/HK - John Wong.png' },
      ],
      clients: [
        {
          id: 159,
          name: 'CCCL',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Jacky Wong'],
          tier: '',
        },
        {
          id: 160,
          name: 'Connect',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'John Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Letters & Thoo',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung',],
          tier: '',
        },
        {
          id: 161,
          name: 'R. Lewis Sanders',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung',],
          tier: '',
        },
        {
          id: 161,
          name: 'Austcham',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Harris Leong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Destination China',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Exellar',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Alvin Luk'],
          tier: '',
        },
        {
          id: 161,
          name: 'Naga',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Sedona',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kay Yeung', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Obsidian',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'TTB (SG)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'Ceratec',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Charlton',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Mother\'s Choice',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong', 'Steve Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Nexus Point',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'SPCA',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong', 'Kenneth Ip'],
          tier: '',
        },
        {
          id: 161,
          name: 'True Fame (LPM)',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Zuma',
          type: 'Recurring',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Cathay Vest',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Horace W',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
        {
          id: 161,
          name: 'Skyway Pacific',
          type: 'Prepaid',
          invoiceText: '',
          coreServices: ['Service Desk'],
          engineeringTeam: ['Samuel Wong'],
          tier: '',
        },
      ],
    },
    {
      id: 26,
      name: 'Casey Tang',
      position: 'Sales Admin',
    company: 'FunctionEight',
      image: '/avatars/HK - Casey Tang.png',
      employees: [
      ],
      clients: [
      ],
    },
  ],
};